export const TOURNAMENTS = [
  {
    id: "1",
    title: "OFC Pineapple",
    gameType: "NL 2-7 TRIPLE DRAW",
    date: "12:00 pm, 28 July",
    status: "registering",
    players: "1000/1000",
    reward: "1000000",
    pinned: true,
    tournamentFeatures: [],
  },
  {
    id: "2",
    title: "OFC Pineapple",
    gameType: "NL Holdem",
    date: "12:00 pm, 28 July",
    status: "registering",
    players: "1/6",
    reward: "100",
    pinned: true,
    tournamentFeatures: [],
  },
  {
    id: "3",
    title: "Hourly Freeroll",
    gameType: "NL OFC/PINEAPPLE PRG",
    date: "12:00 pm, 28 July",
    status: "cancelled",
    players: "1/10 000",
    reward: "1000",
    pinned: true,
    tournamentFeatures: ["Time", "FreeRoll"],
  },
  {
    id: "4",
    title: "OFC Pineapple",
    gameType: "NL Holdem",
    date: "12:00 pm, 28 July",
    status: "cancelled",
    players: "1/6",
    reward: "100",
    pinned: false,
    tournamentFeatures: [],
  },
  {
    id: "5",
    title: "PL Omaha Knockout",
    gameType: "NL 6 CARDS OMAHA H/L",
    date: "12:00 pm, 28 July",
    status: "cancelled",
    players: "0/100",
    reward: "146",
    pinned: false,
    tournamentFeatures: ["Rapid"],
  },
  {
    id: "6",
    title: "Hourly Freeroll",
    gameType: "NL 2-7 TRIPLE DRAW",
    date: "12:00 pm, 28 July",
    status: "registering",
    players: "1/10 000",
    reward: "1000",
    pinned: false,
    tournamentFeatures: [],
  },
];
